export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import "./globals.css";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
